create table if not exists messages (
  id bigint generated by default as identity primary key,
  whatsapp_message_id text unique,
  phone_number text not null,
  direction text not null check (direction in ('inbound', 'outbound')),
  message_type text not null default 'text',
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  name text not null,
  date date not null,
  time text not null,
  adults integer not null check (adults >= 0),
  children integer not null check (children >= 0),
  status text not null default 'confirmed',
  total_people integer,
  booking_reference text,
  calendar_event_id text,
  created_at timestamptz not null default now()
);

alter table bookings add column if not exists booking_reference text;
alter table bookings add column if not exists calendar_event_id text;
alter table bookings add column if not exists total_people integer;
update bookings set total_people = adults + children where total_people is null;
update bookings set booking_reference = 'EL-' || id where booking_reference is null;

create unique index if not exists bookings_reference_idx on bookings(booking_reference) where booking_reference is not null;

create table if not exists booking_audit (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references bookings(id),
  booking_reference text,
  phone_number text not null,
  original_booking jsonb not null,
  updated_booking jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_phone_number_idx on messages(phone_number);
create index if not exists bookings_date_idx on bookings(date);
create index if not exists bookings_slot_idx on bookings(date, time, status);

create or replace function enforce_booking_slot_limit()
returns trigger
language plpgsql
as $$
begin
  if NEW.status = 'confirmed' and (
    select coalesce(sum(coalesce(total_people, adults + children)), 0)
    from bookings
    where date = NEW.date
      and time = NEW.time
      and status = 'confirmed'
      and (TG_OP = 'INSERT' or id <> NEW.id)
  ) + NEW.adults + NEW.children > 30 then
    raise exception 'The people limit for this time slot has been reached';
  end if;
  return NEW;
end;
$$;

drop trigger if exists bookings_slot_limit on bookings;
create trigger bookings_slot_limit
before insert or update on bookings
for each row
execute function enforce_booking_slot_limit();