create table if not exists messages (
  id bigint generated by default as identity primary key,
  whatsapp_message_id text unique,
  phone_number text not null,
  direction text not null check (direction in ('inbound', 'outbound')),
  message_type text not null default 'text',
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  name text not null,
  date date not null,
  time text not null,
  adults integer not null check (adults >= 0),
  children integer not null check (children >= 0),
  status text not null default 'confirmed',
  created_at timestamptz not null default now()
);

create index if not exists messages_phone_number_idx on messages(phone_number);
create index if not exists bookings_date_idx on bookings(date);